alter session set current_schema = mt_toy;
SET heading OFF

SELECT * 
FROM (SELECT CUSTOMER_ID, SUM(TOTAL_AMOUNT) FROM TOY_RENTAL
WHERE TO_CHAR(RENTAL_START_DATE, 'MON-YY') = 'JUN-20'
GROUP BY CUSTOMER_ID
ORDER BY SUM(TOTAL_AMOUNT) DESC)
WHERE ROWNUM = 1;