alter session set current_schema = mt_toy;
SET heading OFF

SELECT * FROM
(SELECT CUSTOMER_NAME FROM CUSTOMER C,
(SELECT TOY_RENTAL.CUSTOMER_ID, SUM(TOY_RENTAL.TOTAL_AMOUNT) AS TOTAL_COST
FROM TOY_RENTAL
GROUP BY TOY_RENTAL.CUSTOMER_ID
ORDER BY TOTAL_COST DESC) R
WHERE C.CUSTOMER_ID = R.CUSTOMER_ID
ORDER BY TOTAL_COST DESC)
WHERE ROWNUM < 3;