alter session set current_schema = mt_toy;
SET heading OFF

SELECT CUSTOMER_NAME
FROM CUSTOMER C, (SELECT CUSTOMER_ID, COUNT(CUSTOMER_ID) FROM TOY_RENTAL R
GROUP BY CUSTOMER_ID
HAVING COUNT(CUSTOMER_ID) > 2) R
WHERE C.CUSTOMER_ID = R.CUSTOMER_ID AND ROWNUM < 3;