alter session set current_schema = mt_toy;
SET heading OFF

SELECT * FROM
(SELECT TOY.TOY_NAME
FROM TOY_RENTAL, TOY
WHERE TOY_RENTAL.TOY_ID = TOY.TOY_ID
ORDER BY (RENTAL_END_DATE - RENTAL_START_DATE) DESC)
WHERE ROWNUM < 2;