alter session set current_schema = mt_toy;
SET heading OFF

SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID IN(SELECT CUSTOMER_ID FROM TOY_RENTAL
WHERE RENTAL_START_DATE < SYSDATE 
GROUP BY CUSTOMER_ID
HAVING(COUNT(CUSTOMER_ID) > 1));