alter session set current_schema = mt_toy;
SET heading OFF

SELECT * FROM
(SELECT TOY_RENTAL.CUSTOMER_ID, COUNT(TOY_RENTAL.RENTAL_ID) AS TOTAL_RENTALS
FROM TOY_RENTAL
GROUP BY TOY_RENTAL.CUSTOMER_ID
ORDER BY TOTAL_RENTALS DESC)
WHERE ROWNUM < 4;