alter session set current_schema = mt_toy;
SET heading OFF

SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID IN(SELECT CUSTOMER_ID FROM TOY_RENTAL
WHERE RENTAL_END_DATE < TO_CHAR(SYSDATE, 'DD-Mon-YY')
AND STATUS = 'Pending'
GROUP BY CUSTOMER_ID);