alter session set current_schema = mt_toy;
SET heading OFF

SELECT T.TOY_ID, TOY_NAME, TOY_TYPE, MIN_AGE, MAX_AGE, PRICE, QUANTITY, RENTAL_AMOUNT
FROM TOY T, CUSTOMER C, TOY_RENTAL R
WHERE C.CUSTOMER_ID = R.CUSTOMER_ID AND T.TOY_ID = T.TOY_ID
AND T.TOY_ID = 5208 OR T.TOY_ID = 5203
GROUP BY RENTAL_AMOUNT, T.TOY_ID, TOY_NAME, TOY_TYPE, MIN_AGE, MAX_AGE, PRICE, QUANTITY;