alter session set current_schema = mt_toy;
SET heading OFF

SELECT CUSTOMER_NAME, CITY, RENTAL_ID, RENTAL_START_DATE, RENTAL_END_DATE
FROM CUSTOMER C, TOY_RENTAL R
WHERE C.CUSTOMER_ID = R.CUSTOMER_ID(+);