alter session set current_schema = mt_toy;
SET heading OFF

SELECT CUSTOMER.CUSTOMER_ID, CUSTOMER_NAME, CITY
FROM CUSTOMER, TOY_RENTAL, TOY
WHERE CUSTOMER.CUSTOMER_ID = TOY_RENTAL.CUSTOMER_ID
AND TOY_RENTAL.TOY_ID = TOY.TOY_ID AND TOY_TYPE = 'Electronics'
ORDER BY CUSTOMER.CUSTOMER_ID;